blank_issues_enabled: false
contact_links:
  - name: Ideas for New Features/Improvements
    url: https://github.com/AmperSoftware/TF-Source-2/discussions
    about: Any new ideas about the project are welcome!
  - name: Chat
    url: https://discord.gg/tMnTsUsVjP
    about: Our Discord server is active, come join us!